name: Test and Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests with coverage
      run: go test ./... -coverprofile=coverage.out -covermode=atomic

    - name: Check test coverage
      run: |
        COVERAGE=$(go tool cover -func=coverage.out | grep total: | awk '{print substr($3, 1, length($3)-1)}')
        echo "Total Coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE < 70.0" | bc -l) )); then
          echo "Coverage is below 70%."
          exit 1
        else
          echo "Coverage is sufficient."
        fi

    - name: Upload coverage to Codecov (optional)
      if: success()
      uses: codecov/codecov-action@v3
      with:
        files: coverage.out
        flags: unittests
        fail_ci_if_error: false
